import {NextRequest,NextResponse} from 'next/server';
import {requireCmsUser} from '@/lib/cms/auth';
import {withCmsTransaction} from '@/lib/cms/db';
import {assertSameOrigin,boundedString,cmsErrorResponse,parseJsonObject,slugValue} from '@/lib/cms/http';

export const runtime='nodejs';
type Context={params:Promise<{id:string}>};
export async function PATCH(request:NextRequest,context:Context){try{assertSameOrigin(request);const user=await requireCmsUser(['SUPER_ADMIN','ADMIN']);const{id}=await context.params;const body=parseJsonObject(await request.json());const name=boundedString(body.name,'name',100,true)!;const slug=slugValue(body.slug);const description=boundedString(body.description,'description',500)||'';const result=await withCmsTransaction(async c=>{const saved=await c.query('UPDATE cms_categories SET name=$2,slug=$3,description=$4,updated_at=now() WHERE id=$1 RETURNING id,name,slug,description',[id,name,slug,description]);if(saved.rowCount)await c.query('INSERT INTO cms_activity_logs(user_id,action,entity,entity_id) VALUES($1,$2,$3,$4)',[user.id,'CATEGORY_UPDATED','CATEGORY',id]);return saved.rows[0]});if(!result)return NextResponse.json({error:'Category not found.'},{status:404});return NextResponse.json({category:result})}catch(error){if(isConflict(error))return NextResponse.json({error:'That category name or slug already exists.'},{status:409});return cmsErrorResponse(error)}}
export async function DELETE(request:NextRequest,context:Context){try{assertSameOrigin(request);const user=await requireCmsUser(['SUPER_ADMIN']);const{id}=await context.params;const result=await withCmsTransaction(async c=>{const used=await c.query('SELECT COUNT(*)::int AS count FROM cms_posts WHERE category_id=$1',[id]);if(used.rows[0]?.count)return 'in_use';const deleted=await c.query('DELETE FROM cms_categories WHERE id=$1 RETURNING id',[id]);if(deleted.rowCount)await c.query('INSERT INTO cms_activity_logs(user_id,action,entity,entity_id) VALUES($1,$2,$3,$4)',[user.id,'CATEGORY_DELETED','CATEGORY',id]);return deleted.rowCount?'deleted':'missing'});if(result==='in_use')return NextResponse.json({error:'Move or delete posts in this category before removing it.'},{status:409});if(result==='missing')return NextResponse.json({error:'Category not found.'},{status:404});return NextResponse.json({ok:true})}catch(error){return cmsErrorResponse(error)}}
function isConflict(error:unknown){return typeof error==='object'&&error!==null&&'code'in error&&error.code==='23505'}
