'use client';

import { useEffect,useState } from 'react';
import { ResourceTable } from '@/components/admin/ResourceTable';

export default function CategoriesPage(){const [name,setName]=useState('');const [slug,setSlug]=useState('');const [description,setDescription]=useState('');const [tag,setTag]=useState('');const [tagSlug,setTagSlug]=useState('');const [notice,setNotice]=useState('');const [refresh,setRefresh]=useState(0);
  async function add(e:React.FormEvent){e.preventDefault();setNotice('');const r=await fetch('/api/admin/categories',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,slug,description})});const b=await r.json();if(!r.ok){setNotice(b.error||'Could not create category');return}setName('');setSlug('');setDescription('');setNotice('Category created.');setRefresh(v=>v+1)}
  async function addTag(e:React.FormEvent){e.preventDefault();setNotice('');const r=await fetch('/api/admin/tags',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:tag,slug:tagSlug})});const b=await r.json();if(!r.ok){setNotice(b.error||'Could not create tag');return}setTag('');setTagSlug('');setNotice('Tag created.');setRefresh(v=>v+1)}
  return <div><h1 className="text-3xl font-semibold">Categories & tags</h1><p className="mt-2 text-sm text-[#64806d]">Organize CMS content. Existing Grow Here categories are seeded by the database migration.</p><form onSubmit={add} className="my-6 grid gap-3 rounded-2xl border border-[#e0e8df] bg-white p-5 md:grid-cols-[1fr_1fr_2fr_auto]"><input required placeholder="Category name" value={name} onChange={e=>{setName(e.target.value);if(!slug)setSlug(e.target.value.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,''))}} className="rounded-lg border border-[#dfe8e0] px-3 py-2 text-sm"/><input required placeholder="slug" value={slug} onChange={e=>setSlug(e.target.value)} className="rounded-lg border border-[#dfe8e0] px-3 py-2 text-sm"/><input placeholder="Description" value={description} onChange={e=>setDescription(e.target.value)} className="rounded-lg border border-[#dfe8e0] px-3 py-2 text-sm"/><button className="rounded-lg bg-[#17603d] px-4 py-2 text-sm font-semibold text-white">Add category</button></form><form onSubmit={addTag} className="my-4 grid gap-3 rounded-2xl border border-[#e0e8df] bg-white p-5 md:grid-cols-[1fr_1fr_auto]"><input required placeholder="Tag name" value={tag} onChange={e=>{setTag(e.target.value);if(!tagSlug)setTagSlug(e.target.value.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,''))}} className="rounded-lg border border-[#dfe8e0] px-3 py-2 text-sm"/><input required placeholder="slug" value={tagSlug} onChange={e=>setTagSlug(e.target.value)} className="rounded-lg border border-[#dfe8e0] px-3 py-2 text-sm"/><button className="rounded-lg border border-[#d5e0d6] px-4 py-2 text-sm font-semibold">Add tag</button></form>{notice&&<p className="mb-4 text-sm text-[#557064]">{notice}</p>}<h2 className="mb-3 mt-7 font-semibold">Categories</h2><ResourceTable key={`categories-${refresh}`} endpoint="/api/admin/categories" collection="categories" columns={[{key:'name',label:'Category'},{key:'slug',label:'Slug'},{key:'description',label:'Description'},{key:'post_count',label:'Posts'}]} empty="No categories yet."/><h2 className="mb-3 mt-7 font-semibold">Tags</h2><ResourceTable key={`tags-${refresh}`} endpoint="/api/admin/tags" collection="tags" columns={[{key:'name',label:'Tag'},{key:'slug',label:'Slug'},{key:'post_count',label:'Posts'}]} empty="No tags yet."/></div>
}
