'use client';

import Link from 'next/link';
import {useEffect,useState} from 'react';
import {useRouter} from 'next/navigation';

type Draft={title:string;slug:string;content:string;status:'DRAFT'|'PUBLISHED'|'ARCHIVED';seoTitle:string;seoDescription:string;canonicalUrl:string};
const blank:Draft={title:'',slug:'',content:'',status:'DRAFT',seoTitle:'',seoDescription:'',canonicalUrl:''};
export function PageEditor({pageId}:{pageId?:string}){const router=useRouter();const[draft,setDraft]=useState(blank);const[slugTouched,setSlugTouched]=useState(Boolean(pageId));const[error,setError]=useState('');const[busy,setBusy]=useState(false);
  useEffect(()=>{if(!pageId)return;fetch(`/api/admin/pages/${pageId}`,{cache:'no-store'}).then(async r=>{const b=await r.json();if(!r.ok)throw new Error(b.error||'Could not load page');const p=b.page;setDraft({title:p.title,slug:p.slug,content:p.content,status:p.status,seoTitle:p.seo_title||'',seoDescription:p.seo_description||'',canonicalUrl:p.canonical_url||''})}).catch(e=>setError(e.message))},[pageId]);
  function change(key:keyof Draft,value:string){setDraft(d=>({...d,[key]:value,...(key==='title'&&!slugTouched?{slug:value.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}:{})}))}
  async function save(status=draft.status){setBusy(true);setError('');try{const r=await fetch(pageId?`/api/admin/pages/${pageId}`:'/api/admin/pages',{method:pageId?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...draft,status})});const b=await r.json();if(!r.ok)throw new Error(b.error||'Could not save page');router.push(`/admin/pages/${b.page.id}`);router.refresh()}catch(e){setError(e instanceof Error?e.message:'Could not save page')}finally{setBusy(false)}}
  async function remove(){if(!pageId||!confirm('Delete this page permanently?'))return;const r=await fetch(`/api/admin/pages/${pageId}`,{method:'DELETE'});if(r.ok)router.push('/admin/pages');else{const b=await r.json();setError(b.error||'Delete failed')}}
  return <div><Link href="/admin/pages" className="text-sm text-[#64806d]">← All pages</Link><div className="mt-2 flex items-end justify-between"><h1 className="text-3xl font-semibold">{pageId?'Edit page':'New page'}</h1><div className="flex gap-2"><button disabled={busy} onClick={()=>save('DRAFT')} className="rounded-xl border bg-white px-4 py-2.5 text-sm">Save draft</button><button disabled={busy} onClick={()=>save('PUBLISHED')} className="rounded-xl bg-[#17603d] px-4 py-2.5 text-sm font-semibold text-white">Publish</button>{pageId&&<button onClick={remove} className="rounded-xl border border-[#e7c5bd] px-4 py-2.5 text-sm text-[#873e31]">Delete</button>}</div></div>{error&&<p role="alert" className="mt-4 text-sm text-[#873e31]">{error}</p>}<section className="mt-6 space-y-5 rounded-2xl border border-[#e0e8df] bg-white p-5 md:p-7">{([['title','Title'],['slug','Slug'],['content','Page content (MDX)'],['seoTitle','SEO title'],['seoDescription','SEO description'],['canonicalUrl','Canonical URL']] as const).map(([key,label])=><label key={key} className="block text-sm font-semibold">{label}{key==='content'?<textarea rows={20} value={draft[key]} onChange={e=>change(key,e.target.value)} className="mt-2 w-full rounded-xl border border-[#dfe8e0] p-3 font-normal leading-6"/>:<input value={draft[key]} onChange={e=>{if(key==='slug')setSlugTouched(true);change(key,e.target.value)}} className="mt-2 w-full rounded-xl border border-[#dfe8e0] p-3 font-normal"/>}</label>)}</section></div>
}
