'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';

type Category={id:string;name:string;slug:string};
type Draft={title:string;slug:string;excerpt:string;content:string;category:string;status:'DRAFT'|'PUBLISHED'|'ARCHIVED';tags:string;featuredImage:string;imageAlt:string;seoTitle:string;seoDescription:string;canonicalUrl:string;openGraphTitle:string;openGraphDescription:string;openGraphImage:string};
const empty:Draft={title:'',slug:'',excerpt:'',content:'',category:'grow',status:'DRAFT',tags:'',featuredImage:'',imageAlt:'',seoTitle:'',seoDescription:'',canonicalUrl:'',openGraphTitle:'',openGraphDescription:'',openGraphImage:''};
const fields:{key:keyof Draft;label:string;large?:boolean;hint?:string}[]=[
  {key:'excerpt',label:'Excerpt',large:true},{key:'content',label:'Article content (MDX)',large:true,hint:'Markdown and existing MDX components are supported. This source editor keeps the current article format intact.'},
  {key:'featuredImage',label:'Featured image path or URL',hint:'Existing images use paths such as /images/posts/example.webp.'},{key:'imageAlt',label:'Image alt text'},
  {key:'tags',label:'Tags (comma separated)'},{key:'seoTitle',label:'SEO title'},{key:'seoDescription',label:'SEO description',large:true},{key:'canonicalUrl',label:'Canonical URL'},
  {key:'openGraphTitle',label:'Open Graph title'},{key:'openGraphDescription',label:'Open Graph description',large:true},{key:'openGraphImage',label:'Open Graph image path or URL'},
];

export function PostEditor({postId}:{postId?:string}){
  const router=useRouter();const [draft,setDraft]=useState<Draft>(empty);const [categories,setCategories]=useState<Category[]>([]);const [slugTouched,setSlugTouched]=useState(Boolean(postId));const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [ready,setReady]=useState(!postId);
  useEffect(()=>{fetch('/api/admin/categories',{cache:'no-store'}).then(async r=>{const b=await r.json();if(!r.ok)throw new Error(b.error||'Could not load categories');setCategories(b.categories);if(!postId&&b.categories[0])setDraft(d=>({...d,category:b.categories[0].slug}));}).catch(e=>setError(e.message));if(postId)fetch(`/api/admin/posts/${postId}`,{cache:'no-store'}).then(async r=>{const b=await r.json();if(!r.ok)throw new Error(b.error||'Could not load post');const p=b.post;setDraft({title:p.title,slug:p.slug,excerpt:p.excerpt,content:p.content,category:p.category,status:p.status,tags:(p.tags||[]).join(', '),featuredImage:p.featured_image||'',imageAlt:p.image_alt||'',seoTitle:p.seo_title||'',seoDescription:p.seo_description||'',canonicalUrl:p.canonical_url||'',openGraphTitle:p.open_graph_title||'',openGraphDescription:p.open_graph_description||'',openGraphImage:p.open_graph_image||''});setSlugTouched(true)}).catch(e=>setError(e.message)).finally(()=>setReady(true));},[postId]);
  function change(key:keyof Draft,value:string){setDraft(d=>({...d,[key]:value,...(key==='title'&&!slugTouched?{slug:value.toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}:{})}))}
  async function save(nextStatus=draft.status){setBusy(true);setError('');try{const payload={...draft,status:nextStatus,tags:draft.tags.split(',').map(t=>t.trim()).filter(Boolean)};const response=await fetch(postId?`/api/admin/posts/${postId}`:'/api/admin/posts',{method:postId?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const body=await response.json();if(!response.ok)throw new Error(body.error||'Save failed');router.push(`/admin/posts/${body.post.id}`);router.refresh()}catch(e){setError(e instanceof Error?e.message:'Save failed')}finally{setBusy(false)}}
  async function remove(){if(!postId||!confirm('Delete this post permanently?'))return;setBusy(true);try{const r=await fetch(`/api/admin/posts/${postId}`,{method:'DELETE'});const b=await r.json();if(!r.ok)throw new Error(b.error||'Delete failed');router.push('/admin/posts')}catch(e){setError(e instanceof Error?e.message:'Delete failed')}finally{setBusy(false)}}
  if(!ready)return <p className="text-sm text-[#718276]">Loading article…</p>;
  return <div><div className="flex flex-wrap items-end justify-between gap-4"><div><Link href="/admin/posts" className="text-sm text-[#64806d] hover:underline">← All posts</Link><h1 className="mt-2 text-3xl font-semibold">{postId?'Edit post':'Create post'}</h1></div><div className="flex gap-2"><button disabled={busy} onClick={()=>save('DRAFT')} className="rounded-xl border border-[#d5e0d6] bg-white px-4 py-2.5 text-sm font-semibold disabled:opacity-50">Save draft</button><button disabled={busy} onClick={()=>save('PUBLISHED')} className="rounded-xl bg-[#17603d] px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{busy?'Saving…':'Publish'}</button>{postId&&<button disabled={busy} onClick={remove} className="rounded-xl border border-[#e7c5bd] px-4 py-2.5 text-sm font-semibold text-[#873e31]">Delete</button>}</div></div>
    {error&&<p role="alert" className="mt-5 rounded-xl border border-[#e7c5bd] bg-white p-4 text-sm text-[#873e31]">{error}</p>}
    <div className="mt-6 grid gap-5 xl:grid-cols-[minmax(0,1fr)_300px]"><section className="space-y-5 rounded-2xl border border-[#e0e8df] bg-white p-5 md:p-7">{[ {key:'title' as const,label:'Title',large:false},{key:'slug' as const,label:'URL slug',large:false},...fields].map(field=><label key={field.key} className="block"><span className="text-sm font-semibold">{field.label}</span>{field.hint&&<span className="mt-1 block text-xs text-[#7b8c80]">{field.hint}</span>}{field.large?<textarea rows={field.key==='content'?22:4} value={draft[field.key]} onChange={e=>change(field.key,e.target.value)} className="mt-2 w-full rounded-xl border border-[#dfe8e0] bg-[#fbfcfa] px-3 py-3 text-sm leading-6 outline-none focus:border-[#6a9b76]"/>:<input value={draft[field.key]} onChange={e=>{if(field.key==='slug')setSlugTouched(true);change(field.key,e.target.value)}} className="mt-2 w-full rounded-xl border border-[#dfe8e0] bg-[#fbfcfa] px-3 py-3 text-sm outline-none focus:border-[#6a9b76]"/>}</label>)}</section>
      <aside className="h-fit space-y-5 rounded-2xl border border-[#e0e8df] bg-white p-5"><label className="block text-sm font-semibold">Category<select value={draft.category} onChange={e=>change('category',e.target.value)} className="mt-2 w-full rounded-xl border border-[#dfe8e0] bg-white px-3 py-3 text-sm">{categories.map(c=><option key={c.id} value={c.slug}>{c.name}</option>)}</select></label><label className="block text-sm font-semibold">Status<select value={draft.status} onChange={e=>change('status',e.target.value)} className="mt-2 w-full rounded-xl border border-[#dfe8e0] bg-white px-3 py-3 text-sm"><option value="DRAFT">Draft</option><option value="PUBLISHED">Published</option><option value="ARCHIVED">Archived</option></select></label><div className="rounded-xl bg-[#f5f8f3] p-4 text-xs leading-5 text-[#687d6d]">The MDX import is staged first. Public blog pages still use their original files until the database import has been verified and the public reader is explicitly switched.</div></aside>
    </div>
  </div>;
}
